name: Deploy to Render

on:
  push:
    branches:
      - main  # Se ejecuta cuando hay cambios en la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST "https://api.render.com/deploy/rnd_ZQB5AZmXwK0IAr9FoprFtJme6NZO" \
          -H "Authorization: Bearer $RENDER_API_KEY"
